### ISSUE TITLE
Repurpose the editor to be a read-only browser action popup

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#112]
The Alpha "popup" UX has been shared by @changecourse in Invision.

@jimporter as discussed yesterday, ideally we can get as much re-use out of the current management / editor UI as possible. 

I was playing around with a popup.html but @linuxwolf suggested perhaps we just load index.html but add media queries. We could/should also make the "full" mode responsive, so this means we don't have to create/maintain two experiences (for now).

What do you think?

Related UI (styles) to solve for at #99 since we want to get as close to the [Photon design system](http://design.firefox.com/photon/welcome.html) as possible

**Comment by jimporter** [comment]
I think we'll want more than just media queries. For example, I think we'd want to be able to see the homepage in the management view no matter what size the window is, whereas we'd *never* want to see the homepage in the doorhanger, since it's just a distraction. Also, we'll need to have some behavioral differences in the doorhanger, especially with the keyboard, and I think that would be really confusing if we based it purely on window size.

**Comment by devinreams** [comment]
The updated design comps for Alpha have stripped away any popup concept (except for unlock #16) so this can be a fast-follow based on more informed product and UX.

Moving out of Alpha and removing assignee for now...

**Comment by devinreams** [comment]
Mock ups for the popup experience are now available here to review: 
https://mozilla.invisionapp.com/share/P6DT2HP8X#/screens/257423172

![Screen Shot 2017-10-09 at 12.59.20 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57002eaed1bf020e0086d809/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236454fa6b7191a379ed0c2e58415d4ebc21254d58eeb9cb74fce36f34985619e8d8395b20ce3e12a8ebd649b803ba20894a80e2efdc1d96fa2137a5dad11b61435c52dcbd4f3fb29843c259f34be64852a1163163e67e316e0a.png)

@jimporter @linuxwolf please take a look and leave Comments in invision when you have a chance. Still not on the list for Alpha but worth looking at early now so @changecourse can make adjustments before we're ready to implement..

**Comment by devinreams** [comment]
This is now happening at #206

**Comment by jimporter** [comment]
@devinreams What's the reasoning for duping all these issues forward? Why not dupe them backward so that we keep the previous discussion we had on these issues around?

**Comment by devinreams** [comment]
The value in the old discussion is minimal, since new issues were created likely _because_ they weren't found nor useful.

The detail in the old ones are superseded and outdated by new designs, requirements, etc. and much more details in the newer ones.

And the old dupes are in the wrong place, priority, etc. whereas the new ones are in the right one and it's less work to re-arrange and less potential to make a mistake.

The new ones can easily see the old, but the thinking is they can be safely archived for historical purposes and _mostly_ ignored.

**Comment by jimporter** [comment]
Anyone on the team can update any part of these bugs to add necessary details (including, but not necessarily, existing comments). What I don't want to see happen is for us to continually create new bugs when things change, since it loses history, and in particular, makes it harder for me to find the things I or others said earlier that may still be relevant. In this case, the discussion about responsive design would be lost unless we make a conscious effort to replicate it or go find it later.

Maybe if these bugs were really long (to the point where it was hard to read through them to find relevant info), it'd be worth closing and reopening a bug with a summary of the past discussion, but I don't think we've hit that point with any of our existing bugs.

**Comment by devinreams** [comment]
>Anyone on the team can update any part of these bugs to add necessary details (including, but not necessarily, existing comments). What I don't want to see happen is for us to continually create new bugs when things change

Agreed completely 💯 on this.

Since this was caught in a triage/clean-up effort I didn't intend to go back and reconcile but agree that new dupes should be the ones closed (not old).

I propose we all agree to this _going forward_: first find existing bugs (don't create forward-dupes) and update the original description, title, and add comments accordingly.

I can imagine in some cases there will be issues from external contributors that we may not want to keep around (edit the description "as if" in the words of that person, versus one of us). For example, Tanvi opened an issue around password generation before @sandysage had outlined her plan. There's not much value in the existing issue so I expect Sandy to forward close that as a duplicate when she spins up her detailed outline (and she is backfilling all of those items now as part of this clean up effort so we avoid this as much as possible going forward).

Does that all sound agreeable from here onward?
