### ISSUE TITLE
Extension built by script is not signed

### ISSUE THREAD

**Issue by jrbenny35** [mozilla-lockbox/lockbox-extension#172]
Using ```npm run-script package``` builds an packages an extension but it is not signed.

We could incorporate something like this: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/web-ext_command_reference#web-ext_sign

**Comment by jimporter** [comment]
We can't use web-ext; we're not building a WebExtension (at least not in the short term). We already have a signing pipeline up and running, but since this project relies on (a small amount of) XPCOM code, we have to use the Mozilla-internal pipeline. Hence, there's no real way for a person to just check out our code and produce a signed XPI.

**Comment by m8ttyB** [comment]
Thanks @jrbenny35 (and @jimporter). For now, use what Testpilot offers and we'll tease out a more complete testing story for beta.

**Comment by jrbenny35** [comment]
> We can't use web-ext; we're not building a WebExtension (at least not in the short term). We already have a signing pipeline up and running, but since this project relies on (a small amount of) XPCOM code, we have to use the Mozilla-internal pipeline. Hence, there's no real way for a person to just check out our code and produce a signed XPI.

That explains a lot, thanks for that.
