### ISSUE TITLE
check in or ignore package-lock.json

### ISSUE THREAD

**Issue by hildjj** [mozilla-lockbox/lockbox-extension#19]
either is fine

**Comment by devinreams** [comment]
We've checked it in with everything included thus far:
https://github.com/mozilla-lockbox/lockbox-extension/blob/master/package-lock.json

...we opted to do so given npm's [own recommendation](https://docs.npmjs.com/files/package-lock.json):

> It describes the exact tree that was generated, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.

>This file is intended to be committed into source repositories...

Are you seeing anything unexpected due to its presence? If so, which version of npm do you have (I'm on 5.2.0)?

**Comment by hildjj** [comment]
Ah, I do notice that it's checked in, and got modified when I did a local npm install and a build, with a relatively-trivial diff:

```diff
diff --git a/package-lock.json b/package-lock.json
index f0d55f4..4587f61 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -2,7 +2,6 @@
   "name": "lockbox",
   "version": "0.1.0-pre",
   "lockfileVersion": 1,
-  "requires": true,
   "dependencies": {
     "abbrev": {
       "version": "1.1.0",
```

**Comment by devinreams** [comment]
@jimporter as we chatted about with @hildjj it looks like your node/npm does sha-1 hashes and mine does sha-512? amongst other things? so weird...

https://github.com/mozilla-lockbox/lockbox-extension/compare/wtf-packagelock

@jimporter @linuxwolf What do you think? Should we just delete and `.gitignore` this since it's not really serving us right now?

**Comment by linuxwolf** [comment]
I suppose we can ignore it for now, but this file really helps with consistency.  I'd like to get the differences worked out before too long.

**Comment by linuxwolf** [comment]
It looks like npm 5.3 (ships with node v8.2.0) changed the hash from SHA-1 to SHA-512.  @jimporter can you check what version of npm you have, and if you can upgrade?

**Comment by devinreams** [comment]
@jimporter Another thread `https://github.com/npm/npm/issues/17749` (intentionally not linking) suggests deleting `node_modules` and re-installing may get you back onto sha-512 integrity.

Do you have a spare minute to check and see?

**Comment by jimporter** [comment]
I think we're keeping this checked-in, since it's helpful for getting the right version of indirect dependencies.

Also, even with a new machine and a completely new checkout of the extension, I still appear to get a lot of sha-1 hashes. I don't know what the issue is here, but it probably doesn't matter too much...
