### ISSUE TITLE
Integrate Redux into extension

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#24]
This may all go together as part of getting something storing/retrieving data at https://github.com/mozilla-lockbox/lockbox-extension/issues/17 but calling it out separate in case it's helpful

**Comment by jimporter** [comment]
Before I forget: Should we have a Redux store in the background context to start, or is one in the management page enough?

**Comment by linuxwolf** [comment]
I'm really not sure.

One one hand, it'll help keep the data flow pattern going, but on the other it feels a like extra overhead, but on the gripping hand it's a little less code than writing a very similarly-patterned dispatcher by hand.

**Comment by jimporter** [comment]
Per the Redux documentation, the *intent* is for an app to have exactly one store, although it supports multiple stores. That would suggest that we should just throw the store in the background scripts and be done with it.

**Comment by linuxwolf** [comment]
Well, yeah, but their doc also assumes you're not hopping between isolated contexts; everything is running in the same origin in the same browser.

If there's just one, I think it best belongs in the UIs.  Otherwise I strongly suspect we'll be building something that looks like redux anyway.  We could also revisit as that code gets laid down.

**Comment by linuxwolf** [comment]
Let's start with redux just in the front-end for now.  We can add it to background scripts if we find ourselves struggling to duplicate the same logic that redux more-or-less just gives us.
