### ISSUE TITLE
Photon - Input Field Styling

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#256]
As detailed in this working draft: http://design.firefox.com/photon/components/input-fields.html

Alignment of our different form field states to the standards listed above.

**Comment by changecourse** [comment]
Aligning our text fields to Photon styling: http://design.firefox.com/photon/components/input-fields.html

As referenced in the designs here: https://mozilla.invisionapp.com/share/MHEBCD4PK#/262155633_1-0-1_Lockbox_Home_-_Add_Entry_-_Unfilled

Also in Zeplin: https://zpl.io/25EMG0J

**Comment by m8ttyB** [comment]
I noticed the `Notes` input field has a different border-color than the other input fields when selected, `#7cddee` vs `#0a84ff`. Is this correct?

<img width="1244" alt="screen shot 2017-11-13 at 10 00 44 am" src="https://user-images.githubusercontent.com/63193/32738613-c1fe0efc-c85a-11e7-92de-113ade791dde.png">

**Comment by devinreams** [comment]
@m8ttyB Good eye 👀 

@changecourse can you please help us determine if this inconsistency is (still) expected or should be updated?

input has a focus that's blue: https://github.com/mozilla-lockbox/lockbox-extension/blob/master/src/webextension/widgets/input.css#L34-L40

text area has a focus that's teal: https://github.com/mozilla-lockbox/lockbox-extension/blob/master/src/webextension/widgets/text-area.css#L19-L23

The code comments suggest these differences were intentional but defer to your understanding and intention around the design system(s) here...

**Comment by changecourse** [comment]
Not intended on my end :) 

I think it makes sense to have all focus states be the Blue50, #0a84ff
