### ISSUE TITLE
Hide or disable the entry search form if user has zero entries?

### ISSUE THREAD

**Issue by pdehaan** [mozilla-lockbox/lockbox-extension#324]
Current behavior feels a bit weird (being able to search with zero entries). Not sure if this is the latest UI spec, but it looks like maybe we should be disabling the form in the zero entries state:
https://mozilla.invisionapp.com/share/5JDP20NYB#/screens/256782985

<img width="838" alt="lockbox_entries" src="https://user-images.githubusercontent.com/557895/32685742-288057d6-c64c-11e7-91e2-d4bc94cb9af4.png">

**Comment by jimporter** [comment]
I'd prefer we keep it, since it shows new users that filtering is an option. I don't see much reason to disable it, since it works fine; it's just a no-op.

**Comment by changecourse** [comment]
I disagree, I think the search should be disabled with 0 entries, especially because we want to limit any potential usability/understanding issues when a user is creating their first entry. Dialing back the search bar, as shown in the invision link below, is one of many things to remove the visual noise from the empty state of lockbox. 

https://mozilla.invisionapp.com/share/MHEBCD4PK#/263643956_1-1-0_Lockbox_Home_-_New_Entry_-_Unfilled

Taking this one step further, I also think we should disable the New Entry button while you're already in a New Entry view (this may have been filed as a bug?), as well as disable the "Save Entry" button until at least one field is filled (since all are optional currently)

**Comment by devinreams** [comment]
@changecourse to help decide what the effects should be. Implementation discussion leaned towards "Disabled" states vs. removal.

**Comment by changecourse** [comment]
Disabled state, rather than removal, makes the most sense. 

40% opacity seems to be the approach as defined in the guidelines for buttons, so I think we should do the same for inputs. 

http://design.firefox.com/photon/components/buttons.html
