### ISSUE TITLE
Replace Nessie with new (light-background) asset

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-extension#329]
Currently, the Nessie asset we are using is optimized for a darker background, so the clouds are getting lost in the background grey. I've reached out to Sean M. for building out an alternate version for use on lighter backgrounds. Once he provides it to me, we can move this into the backlog for consideration.

**Comment by changecourse** [comment]
This is the updated asset from Sean M. 

@devinreams I'm having some trouble previewing it but would love if you could look at it and see if it will work for our needs. Thanks! 

[Nessie_v2.svg.zip](https://github.com/mozilla-lockbox/lockbox-extension/files/1479977/Nessie_v2.svg.zip)

**Comment by devinreams** [comment]
@changecourse here's what it looks like on the grey background color:

<img width="1392" alt="screen shot 2017-11-16 at 12 54 30 pm" src="https://user-images.githubusercontent.com/49511/32912780-5144e5a8-cacd-11e7-8b62-a51820ba1988.png">

<img width="1392" alt="screen shot 2017-11-16 at 12 51 49 pm" src="https://user-images.githubusercontent.com/49511/32912712-20763120-cacd-11e7-8d50-8d7d72ce1cd5.png">

(it's just big because the entire article container is big)

And I assume the rename to Nessie is intentional and the filename should reflect that?

**Comment by changecourse** [comment]
Cool, clouds look better with this version. Yes, name change was intentional, for limitation of Lockie throughout... 

Good to go for resizing & implementation on my end!
