### ISSUE TITLE
Generate passwords prototype to explore user attitudes and behavior interacting with password generation

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#440]
Creating an interactive prototype for testing as part of our exploration of personalized password generation. 

This initial exploration is centered around generating passwords within the context of creating a new entry within the doorhanger. 

. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

**Considerations for this feature...**
- [x] When I’m generating a new password for an account, I want to use one that meets the password requirements, so I can get it right the first time. (Let's confirm the sensible, most common requirements for our default generated password, balancing requirements adherence with trust and memorability) 
- [x] When I create a new password, I want to it be fast, so that I can gain access to my account. (sensible default, controls to adjust secondary)
- [x] When I'm creating a password, I want to be able to edit it, so that it matches the password requirements for the account. (Ability to edit the sensible default)
- [x] When I'm creating a password, I want to use a word from my own head, so that I trust it's secure. (functionality covered by previous consideration)

**Types of Passwords to Create**
- [x] When I'm creating a password, I want to use a passphrase, so that if feels memorable.
- [x] When I create a new password, I want it to be alphanumeric, so that I know it's secure.

**Feelings Around Passwords**
- [x] When I’m saving a password, I want to to be retrievable (my memory or some other way) across browsers, so that it’s wherever I need it to be.
- [ ] When I’m creating a password, I want to use something memorable, so I can remember it. (Maybe only applied to master password, tbd)
- [x] When I save a password, I want to trust that it's secure, so that I know I wont get hacked. (strength of password, security of storage)

**Expectations for Generated Passwords**
- [x] When I create a unique password, I want it to be saved somewhere secure, so that I don't have to reset it.
- [x] When I’m saving a password, I want it to retrievable from any device, so that I maintain access to my accounts. (a given that we'll have access to the chosen password across platforms)

**Comment by changecourse** [comment]
@sandysage we may want to consider breaking this out (as the above description is more emblematic of the Epic for PW generation)

**Comment by changecourse** [comment]
The interactive prototype is about 80-90% of the way there, and nearly ready for UR.

Latest build: https://ericawright.github.io/lockbox-test/

**Comment by sandysage** [comment]
![happy.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dc07ab1a9a2600115c9b6f/125516c66e82c728ace21e0d46e0958a339bc1e5cdf9ad4cae58f3806b1c65267000f72f28d6b07cbc467d565d5f4eae445d0b17aaa8df39baa47e21d40854b088270a36d43703adbf881eba00bc288a4c8db4b88e4ec1fa70.gif)

**Comment by hmcgaw** [comment]
@changecourse  is the design for creating an entry in the doorhanger that exists in the prototype what you're proposing as the solution for the first pass? 

I ask because I need to identify what would be useful about that experience to cover in the user study but right now it's unclear how the user is intended to save the password they've created into the password field on the web form.

**Comment by changecourse** [comment]
Yes... prior to us having autofill, this would be the way we would generate and save... through the doorhanger rather than the ideal of within the context of the form on a given webpage... 

I agree that there isn't a bridge between their doorhanger experience and the intuit account creation form. My thought (in the short term) would be that once the entry is saved, we could populate the form of intuit, faking the appearance of it being auto-filled... I'd like to discuss further.

**Comment by changecourse** [comment]
@sandysage & @hmcgaw based on our conversation today, we'll change the prototype to start at point of PW Generation, rather than opening the doorhanger from default... 

Tickets submitted for these changes to the prototype.

The only outstanding task for this ticket is a content review and revisions; then we'll move the issue accordingly.

**Comment by hmcgaw** [comment]
Just reviewed this against the discussion guide and it looks good in terms of what we've asked for. There may be some minor changes that come out of the pilot sessions (happening tentatively on Feb 20, check research plan for detailed schedule).

**Comment by changecourse** [comment]
Prototype is completed and ready for user testing... Moving to "Done" and closing this issue.

Future edits to the prototype will be handled as part of a separate issue based on feedback from the pilot sessions.
