### ISSUE TITLE
Extension to restore default prefs to leave no traces where possible

### ISSUE THREAD

**Issue by deadsquid** [mozilla-lockbox/lockbox-extension#462]
On install, the Lockbox extension appears to disable "Remember logins and passwords for websites". When the extension is disabled or removed, this preference is not restored to its previous state, and a requirement for add-ons is to leave no traces where possible. The extension shoud track previous state and restore it where appropriate (additionally, when this moves to beta, it'd be great to have a notification for the behavioural change).

**Comment by sandysage** [comment]
When the extension is removed, the preference is restored to its previous state upon restart. We'd need to evaluate:
1. restoring the preference after disable -> restart
2. restoring the preference immediately after remove or disable without requiring a restart

As for informing users, it's on our radar (and a recommendation from Alpha user research). It's my plan to circle back to that after we have login manager import functionality to have a better support message.

**Comment by deadsquid** [comment]
Thanks for the quick reply! I'll retest, as I wasn't seeing restoration on restart, and I confess this is one of those issues I meant to file earlier, and may have been addressed. Will retest and close if appropriate.

**Comment by sandysage** [comment]
Confirmed with @jimporter that default prefs are restored after 'uninstall' and restart. 

- not planning to restore the preference after disable because it's unclear how much of a previous state the user wants to retain in case they want to re-enable
- not planning to restore the preference immediately after remove as we're likely going to have to revisit this code at some point in the near future and will want to make more of an intentional decision around when the prefs are changed
