### ISSUE TITLE
Document differences between flattened management UI model and data storage model

### ISSUE THREAD

**Issue by linuxwolf** [mozilla-lockbox/lockbox-extension#48]
The structure of items in `webextension/manage` do not appear to match the `lockbox-datastore` model. The difference -- and how it is converted to/from -- should be documented.

Expected by `lockbox-datastore`:
```
{
   "id": <string UUID>,
  "string": <string>,
  "created": <string RFC 3339 date-time>,
  "modified": <string RFC 3339 date-time>,
  "entry": {
    "type": "login",
    "username": <string>,
    "password": <string>,
    "notes": <string>
  },
  "history": [ *{
    "created": <string RFC 3339 date-time>,
    "patch": <RFC 7386 json merge patch>
  }]
}
```

Actually used by `./webextension/manage`:
```
{
  "id": <string>,
  "title": <string>,
  "username": <string>,
  "password": <string>
}
```

**Comment by jimporter** [comment]
They actually do conform, but I flatten the structure for `<ItemDetails/>` since that's not actually connected to the datastore and it's just reflecting how the form itself is structured. See here for where the structure is unflattened for storage: https://github.com/mozilla-lockbox/lockbox-extension/blob/master/src/webextension/manage/containers/currentItem.js#L19-L27

**Comment by linuxwolf** [comment]
My apologies.

Would you add a comment about that, to help call it out better?

**Comment by jimporter** [comment]
Sure. Comments are something I've been meaning to add across the board now that things are starting to stabilize a bit.
