### ISSUE TITLE
Provide a quick method of copy/paste when there are one or two results for a URI to help users log into their account quickly

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#520]
No distinction needed at this stage for whether a user types in a search result versus we determine it based on the URI.

Goals: provide a way for people to more-quickly copy the username/password.

**Comment by jimporter** [comment]
@linuxwolf I've been looking at this; one thing that makes this somewhat difficult is that so far, I've attempted to minimize the cases where we hold passwords unencrypted in memory. Currently, this means that we only fetch the *full* item details (including the password) when we load the details view for that item. However, this issue proposes giving users access to the password *before* the details view is opened. The simple solution would be pre-fetching all the passwords, but I'm not entirely comfortable with that.

One option would be to change how our copy buttons work so that, instead of simply passing them a string that they put into the clipboard, it actually initiates a fetch of the full item from the datastore and only *then* puts the data in the clipboard. (We could still do the simple "synchronous copy" when we already have the relevant data available though.)

Do you have any opinions here?

**Comment by linuxwolf** [comment]
@jimporter We should change out copy works; fetch the relevant item, populate the clipboard, forget the item.  The only time we should have the data already cached is from the detailed view in the first place.

I don't think we should be concerned about potential latency here, at least not yet.

**Comment by jimporter** [comment]
@linuxwolf Ok, that's what I was thinking. We could even go a step farther and only have the password in memory when the details view is open *and* the user clicked Show Password, but that's probably a separate issue.

**Comment by linuxwolf** [comment]
I think we can start with documenting it (on the list for the threatened threat-model doc from daily standups), and decide later how much of an issue it really is.

**Comment by jimporter** [comment]
Hm, how did this not get auto-resolved?

**Comment by devinreams** [comment]
>how did this not get auto-resolved?

@jimporter I believe it's because the [auto-close keyword feature](https://help.github.com/articles/closing-issues-using-keywords/) only "connects" on commit messages and PR descriptions, but not PR titles 😔
